services:
  postgres:
    image: postgres:16
    container_name: nuvora-postgres

    environment:
      POSTGRES_DB: nuvora
      POSTGRES_USER: nuvora
      POSTGRES_PASSWORD: nuvoraxcrea
      TZ: Asia/Kolkata

    command: [ "postgres", "-c", "TimeZone=Asia/Kolkata" ]


    ports:
      - "5432:5432"

    volumes:
      - nuvora_pgdata:/var/lib/postgresql/data


volumes:
  nuvora_pgdata: